version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootstrap
    versions:
    - "< 5, >= 4.a"
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.166
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
