language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run typecheck
  - npm run tests
  - npm run lint

jobs:
  include:
    - script:
        - npm run build
        - npm test

stages:
  - test
